-- Alter table, Constraints
-- Add constraints to every column of the INGREDIENTS table, you should use NOT NULL for some columns and unique for other(s)

CREATE TABLE INGREDIENTS (
    NAME VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    CONTAIN_LACTOSE BOOLEAN NOT NULL,
    VEGETARIAN BOOLEAN NOT NULL,
    VEGAN BOOLEAN NOT NULL,
    GLUTEN_FREE BOOLEAN NOT NULL,
    UNIQUE (NAME)
);
--insert Statements
INSERT INTO INGREDIENTS(NAME,CONTAIN_LACTOSE,VEGETARIAN,VEGAN,GLUTEN_FREE)
VALUES("Eggs",false,true,false,true);
INSERT INTO INGRIDIENTS(NAME,CONTAIN_LACTOSE,VEGETERIAN,VEGAN,GLUTEN_FREE)
VALUES("Bread",true,true,true,false);
INSERT INTO INGRIDIENTS(NAME,CONTAIN_LACTOSE,VEGETERIAN,VEGAN,GLUTEN_FREE)
VALUES("Beefparty",true,false,false,true);
INSERT INTO INGRIDIENTS(NAME,CONTAIN_LACTOSE,VEGETERIAN,VEGAN,GLUTEN_FREE)
VALUES("Lettuce",true,false,false,true);
INSERT INTO INGRIDIENTS(NAME,CONTAIN_LACTOSE,VEGETERIAN,VEGAN,GLUTEN_FREE)
VALUES("Yorghurt",true,false,false,true);


